Write a function so that the columns of the output matrix are powers of the input
vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.
HINT: Such a matrix with a geometric progression in each row is named for Alexandre-
Theophile Vandermonde.

In [1]:
import numpy as np

In [2]:
import numpy as np
num = np.array([2,3,4,1])
n = 6

np.vander(num,n)

array([[  32,   16,    8,    4,    2,    1],
       [ 243,   81,   27,    9,    3,    1],
       [1024,  256,   64,   16,    4,    1],
       [   1,    1,    1,    1,    1,    1]])

In [3]:
np.vander(num,n, increasing=True)

array([[   1,    2,    4,    8,   16,   32],
       [   1,    3,    9,   27,   81,  243],
       [   1,    4,   16,   64,  256, 1024],
       [   1,    1,    1,    1,    1,    1]])

In [4]:
np.vander(num,n, increasing= False)

array([[  32,   16,    8,    4,    2,    1],
       [ 243,   81,   27,    9,    3,    1],
       [1024,  256,   64,   16,    4,    1],
       [   1,    1,    1,    1,    1,    1]])

In [5]:
np.vander(num)

array([[ 8,  4,  2,  1],
       [27,  9,  3,  1],
       [64, 16,  4,  1],
       [ 1,  1,  1,  1]])

Problem Statement 2:
Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of
the given sequence is defined as follows:
The moving average sequence has n-k+1 elements as shown below.
The moving averages with k=4 of a ten-value sequence (n=10) is shown below
i 1 2 3 4 5 6 7 8 9 10
===== == == == == == == == == == ==
Input 10 20 30 40 50 60 70 80 90 100
y1 25 = (10+20+30+40)/4
y2 35 = (20+30+40+50)/4
y3 45 = (30+40+50+60)/4
y4 55 = (40+50+60+70)/4
y5 65 = (50+60+70+80)/4
y6 75 = (60+70+80+90)/4
y7 85 = (70+80+90+100)/4
Thus, the moving average sequence has n-k+1=10-4+1=7 values.
Question: Write a function to find moving average in an array over a window:
Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [6]:
def moving_average(num_list,k):
    cumsum, moving_avg_1 =[0], []
    
    for i, x in enumerate(num_list,1):
        cumsum.append(cumsum[i-1]+x) # appending the list by adding values one by one
        
        if i>=k:
            moving_avg= round(((cumsum[i]-cumsum[i-k])/k),2) # calculating moving average 
            
            moving_avg_1.append(moving_avg) # appending the moving average 
    print("Moving Values Average are: ", moving_avg_1)
    print("Length of list n-k+1: ", len(moving_avg_1))

In [7]:
# Testing dataset
num_list= [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
k = 3

moving_average(num_list,k)

Moving Values Average are:  [5.0, 4.67, 5.67, 6.67, 9.67, 28.67, 49.33, 72.67, 84.0, 93.33, 116.33]
Length of list n-k+1:  11
